### PR TITLE
Support wasm components installation

### PR DESCRIPTION
**Pull request by miurahr**
implement #53

### CODE REVIEW

**Comment by Skycoder42** [comment]
I do have some experience in working with WASM. If you want me to, I can "take over" this PR and try to get it to work...

**Comment by miurahr** [comment]
I've got error when test build on CI environment on Linux in topic-support-wasm
 https://github.com/miurahr/aqtinstall/pull/55/commits/ae8760f026f59fd5bbf6877c6502d3dc9c26691c
https://dev.azure.com/miurahr/github/_build/results?buildId=1109&view=logs&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de

```
2019-11-16T11:31:41.8609692Z wasm-ld: error: main.o: machine type must be wasm32
2019-11-16T11:31:41.8623820Z wasm-ld: error: moc_main.o: machine type must be wasm32
2019-11-16T11:31:41.8634577Z wasm-ld: error: main.o: machine type must be wasm32
2019-11-16T11:31:41.8644693Z wasm-ld: error: moc_main.o: machine type must be wasm32
2019-11-16T11:31:41.8664953Z wasm-ld: error: moc_main.o: machine type must be wasm32
2019-11-16T11:31:41.8668349Z wasm-ld: error: main.o: machine type must be wasm32
2019-11-16T11:31:41.8678717Z wasm-ld: error: main.o: machine type must be wasm32
2019-11-16T11:31:41.8690000Z wasm-ld: error: main.o: machine type must be wasm32
2019-11-16T11:31:41.8701022Z wasm-ld: error: main.o: machine type must be wasm32
2019-11-16T11:31:41.8737260Z wasm-ld: error: qsurfaceformat.o: machine type must be wasm32
2019-11-16T11:31:41.8957106Z wasm-ld: error: qguiapplication.o: machine type must be wasm32
2019-11-16T11:31:41.9053586Z wasm-ld: error: qwindow.o: machine type must be wasm32
2019-11-16T11:31:41.9106103Z wasm-ld: error: qscreen.o: machine type must be wasm32
2019-11-16T11:31:41.9201274Z wasm-ld: error: qopenglcontext.o: machine type must be wasm32
2019-11-16T11:31:41.9393896Z wasm-ld: error: qpainter.o: machine type must be wasm32
2019-11-16T11:31:41.9436595Z wasm-ld: error: qmatrix4x4.o: machine type must be wasm32
2019-11-16T11:31:41.9472874Z wasm-ld: error: qopenglfunctions.o: machine type must be wasm32
2019-11-16T11:31:41.9490761Z wasm-ld: error: qopenglpaintdevice.o: machine type must be wasm32
2019-11-16T11:31:41.9600458Z wasm-ld: error: qopenglshaderprogram.o: machine type must be wasm32
2019-11-16T11:31:41.9682049Z wasm-ld: error: qpluginloader.o: machine type must be wasm32
2019-11-16T11:31:41.9837749Z wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
2019-11-16T11:31:41.9861248Z shared:ERROR: '/home/vsts/work/1/b/emsdk/upstream/bin/wasm-ld -o /tmp/emscripten_temp_6jlnfbi6/openglwindow.wasm --allow-undefined --lto-O0 openglwindow.o main.o -L/home/vsts/work/1/b/emsdk/upstream/emscripten/system/local/lib openglwindow.js_plugin_import.o -L/home/vsts/work/1/b/emsdk/upstream/emscripten/system/lib moc_openglwindow.o -L/home/vsts/.emscripten_cache/wasm-obj /home/vsts/work/1/b/Qt/5.14.0/wasm_32/plugins/platforms/libqwasm.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/lib/libQt5EventDispatcherSupport.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/lib/libQt5FontDatabaseSupport.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/lib/libqtfreetype.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/lib/libQt5EglSupport.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/plugins/imageformats/libqgif.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/plugins/imageformats/libqicns.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/plugins/imageformats/libqico.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/plugins/imageformats/libqjpeg.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/plugins/imageformats/libqtga.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/plugins/imageformats/libqtiff.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/plugins/imageformats/libqwbmp.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/plugins/imageformats/libqwebp.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/lib/libQt5Gui.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/lib/libqtlibpng.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/lib/libqtharfbuzz.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/lib/libQt5Core.a /home/vsts/work/1/b/Qt/5.14.0/wasm_32/lib/libqtpcre2.a /home/vsts/.emscripten_cache/wasm-obj/libc.a /home/vsts/.emscripten_cache/wasm-obj/libcompiler_rt.a /home/vsts/.emscripten_cache/wasm-obj/libc-wasm.a /home/vsts/.emscripten_cache/wasm-obj/libc++-noexcept.a /home/vsts/.emscripten_cache/wasm-obj/libc++abi-noexcept.a --whole-archive /home/vsts/.emscripten_cache/wasm-obj/libembind-rtti.a --no-whole-archive /home/vsts/.emscripten_cache/wasm-obj/libgl-webgl2.a /home/vsts/.emscripten_cache/wasm-obj/libdlmalloc.a /home/vsts/.emscripten_cache/wasm-obj/libpthread_stub.a /home/vsts/.emscripten_cache/wasm-obj/libc_rt_wasm.a --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --strip-debug --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location --export fflush --export emscripten_GetProcAddress --export strstr --export emscripten_webgl_make_context_current --export emscripten_webgl_get_current_context --export emscripten_builtin_free --export _get_environ --export emscripten_builtin_memalign --export memalign --export realloc --export _ZSt18uncaught_exceptionv --export __cxa_find_matching_catch --export __cxa_is_pointer_type --export __cxa_can_catch --export strlen --export _get_tzname --export _get_daylight --export _get_timezone -z stack-size=5242880 --initial-memory=16777216 --no-entry --global-base=1024' failed (1)
2019-11-16T11:31:42.0383260Z Makefile:222: recipe for target 'openglwindow.js' failed
2019-11-16T11:31:42.0384428Z make: *** [openglwindow.js] Error 1
```

What wrong?

**Comment by Skycoder42** [comment]
Try again with not the latest emsdk, but the version officially supported by Qt: `sdk-1.38.27-64bit`

See https://doc.qt.io/qt-5/wasm.html for more details. Also I'd recommend you to try with Qt 5.13.2 instead of Qt 5.14, as that one has not been released yet and thus is potentially full of bugs.

**Comment by miurahr** [comment]
wasm in Qt is only support sdk-1.38.27-64bit not latest.

**Comment by miurahr** [comment]
now it seems working. Can I merge it?

**Pull request merged**
