### PR TITLE
Allow path search for 7z

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
The existing code did not search `$PATH` and would reject just `7z` even when it would run fine later on.  My first attempt with `shutil.which()` isn't really great.  Just try, let it fail, catch the exception.  A single subprocess call isn't a huge overhead in this context.

**Comment by altendky** [comment]
This is relevant to using an external 7z command across platforms where paths would vary but it may always be findable in `$PATH`.

**Comment by miurahr** [comment]
Looks good.

**Comment by miurahr** [comment]
Also picked for 0.7.*

**Pull request merged**
