### PR TITLE
search for modules in extensions directory

### PR DESCRIPTION
**Pull request by tsteven4**
This allows install-qt to find and install qtwebengine on mac, windows, linux, linux_arm64 with 6.8.0.  It may work with qtpdf as well.

However, list-qt doesn't find qtwebengine.  I suspect there are other deficiencies.

This is related to #803, #818, #824.

I don't expect this PR to be merged as is, but I offer it

- in the spirit of #818 
- in desperation to get CI running with 6.8.0 for https://github/GPSBabel/gpsbabel.git

Note that 6.8.1 is expected to release in a few days.

### CODE REVIEW

**Comment by Kidev** [comment]
I work on something similar, check out if interested. To make it easier for users, I chose to add all extensions recently moved from modules (Qt 6.8.x) as modules again. So I can do this:
```bash
❯ aqt install-qt windows desktop 6.8.0 win64_msvc2022_64 --modules qtpdf

INFO    : aqtinstall(aqt) v0.1.dev1808 on Python 3.12.7 [CPython GCC 14.2.1 20240910]
INFO    : Found Qt module 'qtpdf' as an extension package
INFO    : Downloading qtdeclarative...
INFO    : Downloading qttools...
INFO    : Downloading qtbase...
INFO    : Redirected: ftp.nluug.nl
INFO    : Redirected: ftp.nluug.nl
INFO    : Redirected: ftp.nluug.nl
INFO    : Downloading qtsvg...
INFO    : Redirected: ftp.nluug.nl
INFO    : Finished installation of qtsvg-Windows-Windows_11_23H2-MSVC2022-Windows-Windows_11_23H2-X86_64.7z in 1.49535746
INFO    : Downloading qttranslations...
INFO    : Redirected: ftp.nluug.nl
INFO    : Finished installation of qttranslations-Windows-Windows_11_23H2-MSVC2022-Windows-Windows_11_23H2-X86_64.7z in 1.33899585
INFO    : Finished installation of qttools-Windows-Windows_11_23H2-MSVC2022-Windows-Windows_11_23H2-X86_64.7z in 3.02215024
INFO    : Downloading d3dcompiler_47...
INFO    : Downloading opengl32sw...
INFO    : Redirected: ftp.nluug.nl
INFO    : Redirected: ftp.nluug.nl
INFO    : Finished installation of d3dcompiler_47-x64.7z in 1.21342271
INFO    : Downloading qtpdf...
INFO    : Redirected: ftp.nluug.nl
INFO    : Finished installation of opengl32sw-64-mesa_11_2_2-signed_sha256.7z in 1.78652537
INFO    : Finished installation of qtbase-Windows-Windows_11_23H2-MSVC2022-Windows-Windows_11_23H2-X86_64.7z in 5.04131050
INFO    : Finished installation of qtpdf-Windows-Windows_11_23H2-MSVC2022-Windows-Windows_11_23H2-X86_64.7z in 1.97751888
```

It is building on top of my PR that fixes WASM for Qt 6.7+ and its still very experimental, but its there: https://github.com/Kidev/aqtinstall/tree/semver

**Comment by tsteven4** [comment]
I added support for "list-qt --modules" and "list-qt --long-modules".

"list-qt --modules" and install-qt are working with qtwebengine and qtpdf in CI on windows and macos with 6.2.4, 6.5.3, and 6.8.0.  There is a [gpsbabel branch](https://github.com/tsteven4/gpsbabel/tree/hackaqt) running CI that uses an [aqt branch](https://github.com/tsteven4/aqtinstall/tree/gpsbabel) that currently matches this PR to install Qt.

**Review by miurahr — CHANGES_REQUESTED** [review]
It looks good enough for me, but there is a little point to be improved.
I want to merge it with the suggested change.

**Review by miurahr — APPROVED** [review]

**Comment by Poldraunic** [comment]
Thank you so much for working on it!

**Pull request merged**
