### PR TITLE
Fix warnings when rendering sphinx docs

### PR DESCRIPTION
**Pull request by ddalcino**
This silences 7 different warnings. See commit messages for the rationale behind each change.

### CODE REVIEW

**Comment by ddalcino** [comment]
https://github.com/miurahr/aqtinstall/blob/bf7b0ee914dc4886a5a5297b7b3345f669b391a5/CHANGELOG.rst#L102-L111

In CHANGELOG.rst, `sphinx.ext.autosectionlabel` makes a duplicate label for every section called 'Added', 'Changed', or 'Fixed'. This triggers ~20 warnings like this:

    CHANGELOG.rst:103: WARNING: duplicate label added, other instance in ./docs/changes.rst

**Comment by miurahr** [comment]
I'd like to drop `sphinx.ext.autosectionlabel` from sphinx configuration.

**Comment by ddalcino** [comment]
> I'd like to drop `sphinx.ext.autosectionlabel` from sphinx configuration.

Ok, we can do that. I'll take it out, and add the labels we need manually.

**Comment by ddalcino** [comment]
Ok, all the warnings are silenced now.

**Pull request merged**
