### PR TITLE
Add support for standalone sdktool installation

### PR DESCRIPTION
**Pull request by luk1337**
This allows us to install sdktool using the following command:
aqt install-tool windows desktop sdktool

### CODE REVIEW

**Comment by miurahr** [comment]
thank you for the proposal! 
when check combinations.json, there are only entries for sdktools.doc not sdktool
https://github.com/miurahr/aqtinstall/blob/master/aqt/combinations.json#L814

Could you also improve CI tool to update the data?
https://github.com/miurahr/aqtinstall/blob/master/ci/generate_combinations.py#L54

`iter_tool_variants` method seems return no "sdktool" variant.

A tool is  called by GitHub Actions
https://github.com/miurahr/aqtinstall/blob/master/.github/workflows/check-combinations.yml

**Comment by luk1337** [comment]
It seems like `ci/generate_combinations.py` is already aware of `sdktool` without doing anything. However, it was failing at `tools_qtdesignstudio_generation2`, which I had to temporarily blacklist when running it.

**Comment by miurahr** [comment]
> It seems like `ci/generate_combinations.py` is already aware of `sdktool` without doing anything. However, it was failing at `tools_qtdesignstudio_generation2`, which I had to temporarily blacklist when running it.

Thank you for the trial. You are welcome to change to add it blacklist in another PR.

**Comment by luk1337** [comment]
> > It seems like `ci/generate_combinations.py` is already aware of `sdktool` without doing anything. However, it was failing at `tools_qtdesignstudio_generation2`, which I had to temporarily blacklist when running it.
> 
> Thank you for the trial. You are welcome to change to add it blacklist in another PR.

Maybe `tools_qtdesignstudio_generation2` will eventually get fixed, it just seems weird that file exists but .sha256 doesn't.
* https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_qtdesignstudio_generation2/Updates.xml
* https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_qtdesignstudio_generation2/Updates.xml.sha256

**Comment by ddalcino** [comment]
> Maybe `tools_qtdesignstudio_generation2` will eventually get fixed, it just seems weird that file exists but .sha256 doesn't work.
> 
>     * https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_qtdesignstudio_generation2/Updates.xml
> 
>     * https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_qtdesignstudio_generation2/Updates.xml.sha256

Unfortunately, missing `.sha256` files are common; it's an existing issue that does not have an easy solution (see #578). However, they are typically missing for less than 24 hours after new files are uploaded. If you check the sha256 link again, you'll find that it's working now.

**Pull request merged**
