### PR TITLE
Fix patching for Qt 6.4.1 android

### LINKED ISSUE #621: aqt installs wrong archive versions for Android
aqt installs Windows or macOS versions of archives, instead of expected Linux-RHEL, when installing for Android.

Running below on Ubuntu 22.04:

```
$ aqt install-qt  linux android 6.4.1 android_armv7  --archives qtbase qtdeclarative qtsvg qttools             --modules qtwebview
INFO    : aqtinstall(aqt) v3.0.2 on Python 3.8.10 [CPython GCC 9.4.0]
WARNING : You are installing the android version of Qt, which requires that the desktop version of Qt is also installed. You can install it with the following command:
          `aqt install-qt linux desktop 6.4.1 gcc_64`
WARNING : Specified Qt version is unknown: 6.4.1.
INFO    : Downloading qtbase...
INFO    : Downloading qtsvg...
INFO    : Downloading qtwebview...
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Downloading qtdeclarative...
INFO    : Finished installation of qtsvg-Windows-Windows_10_21H2-Clang-Android-Android_ANY-ARMv7.7z in 4.70239495
INFO    : Finished installation of qtwebview-Windows-Windows_10_21H2-Clang-Android-Android_ANY-ARMv7.7z in 4.82297651
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Downloading qttools...
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Finished installation of qttools-Windows-Windows_10_21H2-Clang-Android-Android_ANY-ARMv7.7z in 16.33704408
INFO    : Finished installation of qtdeclarative-Windows-Windows_10_21H2-Clang-Android-Android_ANY-ARMv7.7z in 84.48235241
INFO    : Finished installation of qtbase-Windows-Windows_10_21H2-Clang-Android-Android_ANY-ARMv7.7z in 92.03991162
INFO    : Patching /mnt/c/Users/danzv/code/6.4.1/android_arm64_v8a/bin/6.4.1/android_armv7/bin/qmake
INFO    : Finished installation
INFO    : Time elapsed: 95.69257085 second
```

or for android_arm64_v8a:
```
$ cd ..; aqt install-qt  linux android 6.4.1 android_arm64_v8a  --archives qtbase qtdeclarative qtsvg qttools             --modules qtwebview
INFO    : aqtinstall(aqt) v3.0.2 on Python 3.8.10 [CPython GCC 9.4.0]
WARNING : You are installing the android version of Qt, which requires that the desktop version of Qt is also installed. You can install it with the following command:
          `aqt install-qt linux desktop 6.4.1 gcc_64`
WARNING : Specified Qt version is unknown: 6.4.1.
INFO    : Downloading qtsvg...
INFO    : Downloading qtwebview...
INFO    : Downloading qtbase...
INFO    : Downloading qtdeclarative...
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Finished installation of qtwebview-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 8.91114430
INFO    : Finished installation of qtsvg-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 8.87464106
INFO    : Downloading qttools...
INFO    : Redirected: qtproject.mirror.liquidtelecom.com
INFO    : Finished installation of qttools-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 16.88082671
INFO    : Finished installation of qtdeclarative-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 87.06333792
INFO    : Finished installation of qtbase-MacOS-MacOS_12-Clang-Android-Android_ANY-ARM64.7z in 93.44883074
INFO    : Patching /mnt/c/Users/danzv/code/6.4.1/android_arm64_v8a/bin/qmake
INFO    : Finished installation
INFO    : Time elapsed: 97.13789190 second
```

**To Reproduce**
1. using aqt 3.0.2 installed via pip
2. Execute eg: `aqt install-qt  linux android 6.4.1 android_arm64_v8a  --archives qtbase qtdeclarative qtsvg qttools             --modules qtwebview`

**Expected behavior**
Install Linux-RHEL versions rather than randomly selecting macOS and Windows packages.

**`aqt` output**
See above

**Desktop (please complete the following information):**
 - OS: Ubuntu targeting android
 - `aqt` version 3.0.2

### LINKED ISSUE #626: Cannot add Qt 6.4.1 Android Arm64_v8a as a Qt Kit into QtCreator
**Description**
When trying to add Qt 6.4.1 Android Arm64_v8a as a Qt Version for Kit into QtCreator, I am getting an error:

The qmake executable /opt/Qt/6.4.1/android_arm64_v8a/bin/qmake could not be added: "/opt/Qt/6.4.1/android_arm64_v8a/bin/qmake" produced no output: /opt/Qt/6.4.1/android_arm64_v8a/bin/qmake: 7: /Users/qt/work/install/bin/qmake: not found

However, via an official installer I can add this Qt version without any issues and I can compile and deploy everything as usual.

**To Reproduce**
1. aqt install-qt -O /opt/Qt linux android 6.4.1 android_arm64_v8a --autodesktop
2. Open QtCreator 8.0.2, add /opt/Qt/6.4.1/android_arm64_v8a/bin/qmake as Qt Version.
3. See the error.

**Expected behavior**
Works the same as for the official installer.

**Desktop:**
 - OS: Ubuntu 22.04
 - `aqt` version: aqtinstall(aqt) v3.0.2 on Python 3.10.6 [CPython GCC 11.3.0]

UPD:
I don't have such problem with Qt 6.4.0 installed via aqtinstall.

### PR DESCRIPTION
**Pull request by ddalcino**
This will update `updater.py` so that it patches Qt 6.4.1 for android properly.

Fix #626. Fix #621.

### CODE REVIEW

**Comment by ddalcino** [comment]
I'm getting this error in CI when running qmake for Mac, with Qt built for windows (android_armv7):

> \+ qmake /Users/runner/work/1/b/tests/accelbubble
Project ERROR: Cannot run target compiler '/Users/runner/work/1/s/android-ndk-r21e/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++'. Output:
===================
===================
Maybe you forgot to setup the environment?

I get something similar in CI running qmake for Linux, with Qt  built for mac (android_arm64_v8a):

> \+ qmake /home/vsts/work/1/b/tests/accelbubble
Project ERROR: Cannot run target compiler '/home/vsts/work/1/s/android-ndk-r21e/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++'. Output:
===================
===================
Maybe you forgot to setup the environment?

In CI, both of these builds have `android-ndk-r21e` set up properly for their respective environments:
https://github.com/miurahr/aqtinstall/blob/2c8b23d649a0c856dd575cf376438b3e9edf4beb/ci/steps.yml#L154-L161

... but it looks like qmake is looking for the wrong `android-ndk-r21e`. Maybe it's using the wrong mkspecs file by default?

**Comment by ddalcino** [comment]
Now I'm getting this error on Mac, using `android_armv7`, which is built on Windows:

> \+ qmake /Users/runner/work/1/b/tests/accelbubble
Info: creating stash file /Users/runner/work/1/s/.qmake.stash
sh: /Users/runner/work/1/b/Qt/6.4.1/macos/bin/rcc: No such file or directory
\+ make
...
make: *** No rule to make target '../b/Qt/6.4.1/macos/bin/rcc', needed by 'qrc_qml.cpp'.  Stop.

For some reason, Make is looking for `rcc` in the bin directory. When I install Qt 6.4.1 for Windows desktop, I get `rcc.exe` installed in the `6.4.1/<arch>/bin` directory. Qt desktop for Linux and Mac do not include any `rcc` file in the `6.4.1/<arch>/bin` directory.

I'm not sure what's going on here, or how to fix it. If anyone has any ideas, please post them here!

**Comment by ddalcino** [comment]
> For some reason, Make is looking for `rcc` in the bin directory. When I install Qt 6.4.1 for Windows desktop, I get `rcc.exe` installed in the `6.4.1/<arch>/bin` directory. Qt desktop for Linux and Mac do not include any `rcc` file in the `6.4.1/<arch>/bin` directory.

`rcc` is the resource compiler, and on Mac it exists at `6.4.1/macos/libexec/rcc`. Qt for linux has it installed at `6.4.1/gcc_64/libexec/rcc`. Not sure what needs to change here to have `make` look for it in the right location.

**Comment by ddalcino** [comment]
For future reference, there's a "cheat code" to adding support for new versions of Qt: read the diff between `installscript.qs` between the last version and the new version. The diff between 6.4.0 and 6.4.1 explains everything that changed.

**Comment by miurahr** [comment]
Thank you so much!

**Pull request merged**
