### PR TITLE
fix source/doc/examples with qstkdrepo changes.

### LINKED ISSUE #843: [Bug]: Fails to install-src for Qt 6.8.1 on Linux
### Bug description

When attempting to install the source code for Qt 6.8.1 on Linux, it fails to find the Update.xml file.

I am working inside a fresh docker container with python (e.g., `docker run -it python /bin/bash`). Inside the container, I execute `pip install aqtinstall` followed by `aqt install-src linux 6.8.1`, which leads to the error message reported below.

This might be related to #810?

### Expected behavior

Installing source code for Qt 6.8.1 should not cause an error.

### aqt and python version

v3.1.19 with Python 3.12.4

### Operating System

Linux/Unix

### Relevant log output

```shell
root@43354294a782:/# aqt install-src -O /build-qt linux 6.8.1
INFO    : aqtinstall(aqt) v3.1.19 on Python 3.12.4 [CPython GCC 12.2.0]
WARNING : Failed to download checksum for the file 'Updates.xml'. This may happen on unofficial mirrors.
ERROR   : Failed to locate XML data for Qt version '6.8.1'.
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt all_os qt' to show versions available.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tsteven4**
This handles all_os/qt/qt6_xyz_src_doc_examples changing to all_os/qt/qt6/xyz/[unix|windows]_line_endings_src for both list and install commands.

This resolves #843

### CODE REVIEW

**Comment by Kidev** [comment]
This will clash massively with #846

**Comment by tsteven4** [comment]
It fixes issues with: install-src, install-example, install-doc, list-src, list-example, list-doc

**Comment by Kidev** [comment]
@tsteven4 Changes to `to_folder` may clash after review. Can you try to get it to work from #846 ? It entirely works since a few days, the latest changes are related to CI

**Comment by tsteven4** [comment]
> This is my version, does it fix your issue already? It may

@Kidev  Your change to to_folder breaks my fix for source/doc/examples.  When we get src/doc/example listings from all_os/qt (>= 6.7.0) we need to use the old style path WITH the extension.  Your change works for 6.7.*, but  not >=6.8.0.  A merge of to_folder will be required.

```
$ aqt list-example linux 6.8.1
ERROR   : Failed to download checksum for the file 'Updates.xml' from mirrors '['https://download.qt.io']
==============================Suggested follow-up:==============================
* Check your internet connection
* Consider modifying `requests.max_retries_to_retrieve_hash` in settings.ini
* Consider modifying `mirrors.trusted_mirrors` in settings.ini (see https://aqtinstall.readthedocs.io/en/stable/configuration.html#configuration)
usage: aqt [-h] [-c CONFIG]
           {install-qt,install-tool,install-doc,install-example,install-src,list-qt,list-tool,list-doc,list-example,list-src,help,version} ...

Another unofficial Qt Installer.
aqt helps you install Qt SDK, tools, examples and others

options:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        Configuration ini file.

subcommands:
  aqt accepts several subcommands:
  install-* subcommands are commands that install components
  list-* subcommands are commands that show available components

  {install-qt,install-tool,install-doc,install-example,install-src,list-qt,list-tool,list-doc,list-example,list-src,help,version}
                        Please refer to each help message by using '--help' with each subcommand
(aqttest-venv) tsteven4@PEDALDAMNIT:~/work/tsaqt$ tail aqtinstall.log
2024-12-18 01:41:24,709 - aqt.helper - DEBUG - helper 140359476011136 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/all_os/qt/qt6_681/qt6_681/Updates.xml.sha256
2024-12-18 01:41:25,356 - aqt.helper - DEBUG - helper 140359476011136 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/all_os/qt/qt6_681/qt6_681/Updates.xml.sha256
2024-12-18 01:41:26,153 - aqt.helper - DEBUG - helper 140359476011136 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/all_os/qt/qt6_681/qt6_681/Updates.xml.sha256
2024-12-18 01:41:26,792 - aqt.helper - DEBUG - helper 140359476011136 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/all_os/qt/qt6_681/qt6_681/Updates.xml.sha256
2024-12-18 01:41:27,449 - aqt.helper - DEBUG - helper 140359476011136 Attempt to download checksum at https://download.qt.io/online/qtsdkrepository/all_os/qt/qt6_681/qt6_681/Updates.xml.sha256
2024-12-18 01:41:28,092 - aqt.main - ERROR - installer 140359476011136 Failed to download checksum for the file 'Updates.xml' from mirrors '['https://download.qt.io']
==============================Suggested follow-up:==============================
* Check your internet connection
* Consider modifying `requests.max_retries_to_retrieve_hash` in settings.ini
* Consider modifying `mirrors.trusted_mirrors` in settings.ini (see https://aqtinstall.readthedocs.io/en/stable/configuration.html#configuration)
```

I tested this PR with this your change to to_folder:
```
$ git diff
diff --git a/aqt/metadata.py b/aqt/metadata.py
index 3783101..4c76c98 100644
--- a/aqt/metadata.py
+++ b/aqt/metadata.py
@@ -276,20 +276,28 @@ class ArchiveId:
         )

     def to_folder(self, version: Version, qt_version_no_dots: str, extension: Optional[str] = None) -> str:
-        if (version >= Version("6.8.0")) and not ((self.host == "all_os") and (self.target == "qt")):
-            return "{category}{major}_{ver}/{category}{major}_{ver}{ext}".format(
-                category=self.category,
-                major=qt_version_no_dots[0],
-                ver=qt_version_no_dots,
-                ext="_" + extension if extension else "",
-            )
-        else:
-            return "{category}{major}_{ver}{ext}".format(
-                category=self.category,
-                major=qt_version_no_dots[0],
-                ver=qt_version_no_dots,
-                ext="_" + extension if extension else "",
-            )
+        if version >= Version("6.8.0"):
+            if self.target == "wasm":
+                # Qt 6.8+ WASM uses a split folder structure
+                folder = f"qt{version.major}_{qt_version_no_dots}"
+                if extension:
+                    folder = f"{folder}/{folder}_{extension}"
+                return folder
+            else:
+                base = f"qt{version.major}_{qt_version_no_dots}"
+                return f"{base}/{base}"
+        elif version >= Version("6.5.0") and self.target == "wasm":
+            # Qt 6.5-6.7 WASM uses direct wasm_[single|multi]thread folder
+            if extension:
+                return f"qt{version.major}_{qt_version_no_dots}_{extension}"
+            return f"qt{version.major}_{qt_version_no_dots}"
+        # Pre-6.8 structure for non-WASM or pre-6.5 structure
+        return "{category}{major}_{ver}{ext}".format(
+            category=self.category,
+            major=qt_version_no_dots[0],
+            ver=qt_version_no_dots,
+            ext="_" + extension if extension else "",
+        )

     def all_extensions(self, version: Version) -> List[str]:
         if self.target == "desktop" and QtRepoProperty.is_in_wasm_range(self.host, version):
```

**Review by miurahr — CHANGES_REQUESTED** [review]
There are several linter warnings reported. Could you improve the code style and a usage of `Version`?

**Comment by tsteven4** [comment]
locally pylint 3.3.2 comes up with 168 issues in metadata.py.  Perhaps reviewdog is only showing ones that overlap changes in the file.  55 of these are "line to long".  .flake8 sets the max line length to 125, but pylint seems to use 100.

**Comment by miurahr** [comment]
> locally pylint 3.3.2 comes up with 168 issues in metadata.py. Perhaps reviewdog is only showing ones that overlap changes in the file. 55 of these are "line to long". .flake8 sets the max line length to 125, but pylint seems to use 100.

OK, I see. I do check the configuration of pylint and the PR looks good.

**Review by miurahr — APPROVED** [review]

**Pull request merged**
