### PR TITLE
Run gravitybee with pyproject.toml

### LINKED ISSUE #564: Trying to install it on windows I get the error: "No module named 'aqt.version'"
Hi,

First of all I apologise, I think my problem is simply because I don't know how to use aqtinstall properly. I am trying to install it on windows. I just download aqt.exe and when I try to execute aqt in windows a get a error, any call to aqt gives the same error  (aqt help or aqt list-qt windows desktop).

Thanks in advance

```
C:\Users\Daniel\Downloads>aqt help
Traceback (most recent call last):
  File "daa144671dcb11ed_aqt.py", line 33, in <module>
  File "daa144671dcb11ed_aqt.py", line 25, in importlib_load_entry_point
  File "importlib\metadata.py", line 86, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "aqt\__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'aqt.version'
[11040] Failed to execute script 'daa144671dcb11ed_aqt' due to unhandled exception!

```

### PR DESCRIPTION
**Pull request by miurahr**
- Try to fix #564
- Introduce build-standalone.py that trick gravitybee with modern python build
- update CI scripts

### CODE REVIEW

**Comment by miurahr** [comment]
> Sorry for neglecting this previously; were you able to find out WHY pip no longer generates that console_script anymore? I could not find anything in the docs.

pip generate an EXECUTABLE instead of shell script/batch file.

**Comment by nikitalita** [comment]
Was this change documented anywhere? I want to demonstrate this to the author of gravitybee that pip no longer does this so that they fix this issue.

**Comment by miurahr** [comment]
> Was this change documented anywhere? I want to demonstrate this to the author of gravitybee that pip no longer does this so that they fix this issue.

I cannot find a document, I just observe it.

**Comment by miurahr** [comment]
Is this issue related?
https://github.com/pypa/setuptools/issues/2282

**Comment by miurahr** [comment]
when running `pip install .` instead of `pip install -e .`, I observe aqt script generated.

**Pull request merged**
